// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: game_save.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameSaveDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveId       int64  `protobuf:"varint,1,opt,name=saveId,proto3" json:"saveId,omitempty"`
	RoomId       int64  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	EmulatorId   int64  `protobuf:"varint,3,opt,name=emulatorId,proto3" json:"emulatorId,omitempty"`
	GameId       int64  `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AddTime      string `protobuf:"bytes,6,opt,name=addTime,proto3" json:"addTime,omitempty"`
	RoomName     string `protobuf:"bytes,7,opt,name=roomName,proto3" json:"roomName,omitempty"`
	EmulatorName string `protobuf:"bytes,8,opt,name=emulatorName,proto3" json:"emulatorName,omitempty"`
	GameName     string `protobuf:"bytes,9,opt,name=gameName,proto3" json:"gameName,omitempty"`
}

func (x *GameSaveDto) Reset() {
	*x = GameSaveDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSaveDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSaveDto) ProtoMessage() {}

func (x *GameSaveDto) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSaveDto.ProtoReflect.Descriptor instead.
func (*GameSaveDto) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{0}
}

func (x *GameSaveDto) GetSaveId() int64 {
	if x != nil {
		return x.SaveId
	}
	return 0
}

func (x *GameSaveDto) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GameSaveDto) GetEmulatorId() int64 {
	if x != nil {
		return x.EmulatorId
	}
	return 0
}

func (x *GameSaveDto) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameSaveDto) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

func (x *GameSaveDto) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GameSaveDto) GetEmulatorName() string {
	if x != nil {
		return x.EmulatorName
	}
	return ""
}

func (x *GameSaveDto) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

type ListGameSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	EmulatorId int64 `protobuf:"varint,2,opt,name=emulatorId,proto3" json:"emulatorId,omitempty"`
	GameId     int64 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Page       int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   int32 `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *ListGameSaveRequest) Reset() {
	*x = ListGameSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGameSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameSaveRequest) ProtoMessage() {}

func (x *ListGameSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameSaveRequest.ProtoReflect.Descriptor instead.
func (*ListGameSaveRequest) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{1}
}

func (x *ListGameSaveRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListGameSaveRequest) GetEmulatorId() int64 {
	if x != nil {
		return x.EmulatorId
	}
	return 0
}

func (x *ListGameSaveRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ListGameSaveRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGameSaveRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListGameSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*GameSaveDto `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total   int32          `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListGameSaveResponse) Reset() {
	*x = ListGameSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGameSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameSaveResponse) ProtoMessage() {}

func (x *ListGameSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameSaveResponse.ProtoReflect.Descriptor instead.
func (*ListGameSaveResponse) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{2}
}

func (x *ListGameSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListGameSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListGameSaveResponse) GetData() []*GameSaveDto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListGameSaveResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteGameSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveId int64 `protobuf:"varint,1,opt,name=saveId,proto3" json:"saveId,omitempty"`
}

func (x *DeleteGameSaveRequest) Reset() {
	*x = DeleteGameSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameSaveRequest) ProtoMessage() {}

func (x *DeleteGameSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameSaveRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameSaveRequest) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteGameSaveRequest) GetSaveId() int64 {
	if x != nil {
		return x.SaveId
	}
	return 0
}

type DeleteGameSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteGameSaveResponse) Reset() {
	*x = DeleteGameSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGameSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameSaveResponse) ProtoMessage() {}

func (x *DeleteGameSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameSaveResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameSaveResponse) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGameSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteGameSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveId int64 `protobuf:"varint,1,opt,name=saveId,proto3" json:"saveId,omitempty"`
}

func (x *LoadSaveRequest) Reset() {
	*x = LoadSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSaveRequest) ProtoMessage() {}

func (x *LoadSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSaveRequest.ProtoReflect.Descriptor instead.
func (*LoadSaveRequest) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{5}
}

func (x *LoadSaveRequest) GetSaveId() int64 {
	if x != nil {
		return x.SaveId
	}
	return 0
}

type LoadSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LoadSaveResponse) Reset() {
	*x = LoadSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSaveResponse) ProtoMessage() {}

func (x *LoadSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSaveResponse.ProtoReflect.Descriptor instead.
func (*LoadSaveResponse) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{6}
}

func (x *LoadSaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoadSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SaveGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *SaveGameRequest) Reset() {
	*x = SaveGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameRequest) ProtoMessage() {}

func (x *SaveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameRequest.ProtoReflect.Descriptor instead.
func (*SaveGameRequest) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{7}
}

func (x *SaveGameRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type SaveGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SaveGameResponse) Reset() {
	*x = SaveGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_save_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameResponse) ProtoMessage() {}

func (x *SaveGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_save_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameResponse.ProtoReflect.Descriptor instead.
func (*SaveGameResponse) Descriptor() ([]byte, []int) {
	return file_game_save_proto_rawDescGZIP(), []int{8}
}

func (x *SaveGameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SaveGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_save_proto protoreflect.FileDescriptor

var file_game_save_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7f, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x22, 0x40,
	0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x29, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x10, 0x53,
	0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x89, 0x03,
	0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x5c, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x2d, 0x73, 0x61, 0x76, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x2a, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x61, 0x76, 0x65, 0x2f, 0x7b, 0x73, 0x61,
	0x76, 0x65, 0x49, 0x64, 0x7d, 0x12, 0x58, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x61, 0x76,
	0x65, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x61, 0x76, 0x65, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x58, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01,
	0x2a, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d,
	0x73, 0x61, 0x76, 0x65, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_save_proto_rawDescOnce sync.Once
	file_game_save_proto_rawDescData = file_game_save_proto_rawDesc
)

func file_game_save_proto_rawDescGZIP() []byte {
	file_game_save_proto_rawDescOnce.Do(func() {
		file_game_save_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_save_proto_rawDescData)
	})
	return file_game_save_proto_rawDescData
}

var file_game_save_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_save_proto_goTypes = []any{
	(*GameSaveDto)(nil),            // 0: v1.GameSaveDto
	(*ListGameSaveRequest)(nil),    // 1: v1.ListGameSaveRequest
	(*ListGameSaveResponse)(nil),   // 2: v1.ListGameSaveResponse
	(*DeleteGameSaveRequest)(nil),  // 3: v1.DeleteGameSaveRequest
	(*DeleteGameSaveResponse)(nil), // 4: v1.DeleteGameSaveResponse
	(*LoadSaveRequest)(nil),        // 5: v1.LoadSaveRequest
	(*LoadSaveResponse)(nil),       // 6: v1.LoadSaveResponse
	(*SaveGameRequest)(nil),        // 7: v1.SaveGameRequest
	(*SaveGameResponse)(nil),       // 8: v1.SaveGameResponse
}
var file_game_save_proto_depIdxs = []int32{
	0, // 0: v1.ListGameSaveResponse.data:type_name -> v1.GameSaveDto
	1, // 1: v1.GameSave.ListGameSave:input_type -> v1.ListGameSaveRequest
	3, // 2: v1.GameSave.DeleteGameSave:input_type -> v1.DeleteGameSaveRequest
	5, // 3: v1.GameSave.LoadSave:input_type -> v1.LoadSaveRequest
	7, // 4: v1.GameSave.SaveGame:input_type -> v1.SaveGameRequest
	2, // 5: v1.GameSave.ListGameSave:output_type -> v1.ListGameSaveResponse
	4, // 6: v1.GameSave.DeleteGameSave:output_type -> v1.DeleteGameSaveResponse
	6, // 7: v1.GameSave.LoadSave:output_type -> v1.LoadSaveResponse
	8, // 8: v1.GameSave.SaveGame:output_type -> v1.SaveGameResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_save_proto_init() }
func file_game_save_proto_init() {
	if File_game_save_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_save_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GameSaveDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListGameSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListGameSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGameSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGameSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LoadSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LoadSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SaveGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_save_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SaveGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_save_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_save_proto_goTypes,
		DependencyIndexes: file_game_save_proto_depIdxs,
		MessageInfos:      file_game_save_proto_msgTypes,
	}.Build()
	File_game_save_proto = out.File
	file_game_save_proto_rawDesc = nil
	file_game_save_proto_goTypes = nil
	file_game_save_proto_depIdxs = nil
}
