// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: game.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_OpenGameInstance_FullMethodName           = "/v1.Game/OpenGameInstance"
	Game_GetRoomInstanceAccessToken_FullMethodName = "/v1.Game/GetRoomInstanceAccessToken"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameClient interface {
	OpenGameInstance(ctx context.Context, in *OpenGameInstanceRequest, opts ...grpc.CallOption) (*OpenGameInstanceResponse, error)
	GetRoomInstanceAccessToken(ctx context.Context, in *GetRoomInstanceAccessTokenRequest, opts ...grpc.CallOption) (*GetRoomInstanceAccessTokenResponse, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) OpenGameInstance(ctx context.Context, in *OpenGameInstanceRequest, opts ...grpc.CallOption) (*OpenGameInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenGameInstanceResponse)
	err := c.cc.Invoke(ctx, Game_OpenGameInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetRoomInstanceAccessToken(ctx context.Context, in *GetRoomInstanceAccessTokenRequest, opts ...grpc.CallOption) (*GetRoomInstanceAccessTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomInstanceAccessTokenResponse)
	err := c.cc.Invoke(ctx, Game_GetRoomInstanceAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
type GameServer interface {
	OpenGameInstance(context.Context, *OpenGameInstanceRequest) (*OpenGameInstanceResponse, error)
	GetRoomInstanceAccessToken(context.Context, *GetRoomInstanceAccessTokenRequest) (*GetRoomInstanceAccessTokenResponse, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) OpenGameInstance(context.Context, *OpenGameInstanceRequest) (*OpenGameInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenGameInstance not implemented")
}
func (UnimplementedGameServer) GetRoomInstanceAccessToken(context.Context, *GetRoomInstanceAccessTokenRequest) (*GetRoomInstanceAccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomInstanceAccessToken not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call pancis, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_OpenGameInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenGameInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).OpenGameInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_OpenGameInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).OpenGameInstance(ctx, req.(*OpenGameInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetRoomInstanceAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomInstanceAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetRoomInstanceAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_GetRoomInstanceAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetRoomInstanceAccessToken(ctx, req.(*GetRoomInstanceAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenGameInstance",
			Handler:    _Game_OpenGameInstance_Handler,
		},
		{
			MethodName: "GetRoomInstanceAccessToken",
			Handler:    _Game_GetRoomInstanceAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
