// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: room_instance.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomInstanceDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInstanceId int64  `protobuf:"varint,1,opt,name=roomInstanceId,proto3" json:"roomInstanceId,omitempty"`
	RoomId         int64  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	EmulatorId     int64  `protobuf:"varint,3,opt,name=emulatorId,proto3" json:"emulatorId,omitempty"`
	EmulatorName   string `protobuf:"bytes,4,opt,name=emulatorName,proto3" json:"emulatorName,omitempty"`
	ServerUrl      string `protobuf:"bytes,5,opt,name=serverUrl,proto3" json:"serverUrl,omitempty"`
}

func (x *RoomInstanceDto) Reset() {
	*x = RoomInstanceDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInstanceDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInstanceDto) ProtoMessage() {}

func (x *RoomInstanceDto) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInstanceDto.ProtoReflect.Descriptor instead.
func (*RoomInstanceDto) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInstanceDto) GetRoomInstanceId() int64 {
	if x != nil {
		return x.RoomInstanceId
	}
	return 0
}

func (x *RoomInstanceDto) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInstanceDto) GetEmulatorId() int64 {
	if x != nil {
		return x.EmulatorId
	}
	return 0
}

func (x *RoomInstanceDto) GetEmulatorName() string {
	if x != nil {
		return x.EmulatorName
	}
	return ""
}

func (x *RoomInstanceDto) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

type GetRoomInstanceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInstance *RoomInstanceDto `protobuf:"bytes,1,opt,name=roomInstance,proto3" json:"roomInstance,omitempty"`
	AccessToken  string           `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
}

func (x *GetRoomInstanceResult) Reset() {
	*x = GetRoomInstanceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInstanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInstanceResult) ProtoMessage() {}

func (x *GetRoomInstanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInstanceResult.ProtoReflect.Descriptor instead.
func (*GetRoomInstanceResult) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomInstanceResult) GetRoomInstance() *RoomInstanceDto {
	if x != nil {
		return x.RoomInstance
	}
	return nil
}

func (x *GetRoomInstanceResult) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetRoomInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int64  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	EmulatorId int64  `protobuf:"varint,2,opt,name=emulatorId,proto3" json:"emulatorId,omitempty"`
	GameFile   string `protobuf:"bytes,3,opt,name=gameFile,proto3" json:"gameFile,omitempty"`
}

func (x *GetRoomInstanceRequest) Reset() {
	*x = GetRoomInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInstanceRequest) ProtoMessage() {}

func (x *GetRoomInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInstanceRequest) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomInstanceRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetRoomInstanceRequest) GetEmulatorId() int64 {
	if x != nil {
		return x.EmulatorId
	}
	return 0
}

func (x *GetRoomInstanceRequest) GetGameFile() string {
	if x != nil {
		return x.GameFile
	}
	return ""
}

type GetRoomInstanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *GetRoomInstanceResult `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetRoomInstanceResponse) Reset() {
	*x = GetRoomInstanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInstanceResponse) ProtoMessage() {}

func (x *GetRoomInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInstanceResponse) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomInstanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRoomInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoomInstanceResponse) GetData() *GetRoomInstanceResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListGameHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *ListGameHistoryRequest) Reset() {
	*x = ListGameHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGameHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameHistoryRequest) ProtoMessage() {}

func (x *ListGameHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListGameHistoryRequest) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{4}
}

func (x *ListGameHistoryRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListGameHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGameHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListGameHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*RoomInstanceDto `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total   int32              `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListGameHistoryResponse) Reset() {
	*x = ListGameHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_instance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGameHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameHistoryResponse) ProtoMessage() {}

func (x *ListGameHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_instance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListGameHistoryResponse) Descriptor() ([]byte, []int) {
	return file_room_instance_proto_rawDescGZIP(), []int{5}
}

func (x *ListGameHistoryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListGameHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListGameHistoryResponse) GetData() []*RoomInstanceDto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListGameHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_room_instance_proto protoreflect.FileDescriptor

var file_room_instance_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x72, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x74,
	0x6f, 0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x6c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x22,
	0x76, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x17, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x74, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x32, 0xec, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x71,
	0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d,
	0x2d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_instance_proto_rawDescOnce sync.Once
	file_room_instance_proto_rawDescData = file_room_instance_proto_rawDesc
)

func file_room_instance_proto_rawDescGZIP() []byte {
	file_room_instance_proto_rawDescOnce.Do(func() {
		file_room_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_instance_proto_rawDescData)
	})
	return file_room_instance_proto_rawDescData
}

var file_room_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_room_instance_proto_goTypes = []any{
	(*RoomInstanceDto)(nil),         // 0: v1.RoomInstanceDto
	(*GetRoomInstanceResult)(nil),   // 1: v1.GetRoomInstanceResult
	(*GetRoomInstanceRequest)(nil),  // 2: v1.GetRoomInstanceRequest
	(*GetRoomInstanceResponse)(nil), // 3: v1.GetRoomInstanceResponse
	(*ListGameHistoryRequest)(nil),  // 4: v1.ListGameHistoryRequest
	(*ListGameHistoryResponse)(nil), // 5: v1.ListGameHistoryResponse
}
var file_room_instance_proto_depIdxs = []int32{
	0, // 0: v1.GetRoomInstanceResult.roomInstance:type_name -> v1.RoomInstanceDto
	1, // 1: v1.GetRoomInstanceResponse.data:type_name -> v1.GetRoomInstanceResult
	0, // 2: v1.ListGameHistoryResponse.data:type_name -> v1.RoomInstanceDto
	2, // 3: v1.RoomInstance.GetRoomInstance:input_type -> v1.GetRoomInstanceRequest
	4, // 4: v1.RoomInstance.ListGameHistory:input_type -> v1.ListGameHistoryRequest
	3, // 5: v1.RoomInstance.GetRoomInstance:output_type -> v1.GetRoomInstanceResponse
	5, // 6: v1.RoomInstance.ListGameHistory:output_type -> v1.ListGameHistoryResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_room_instance_proto_init() }
func file_room_instance_proto_init() {
	if File_room_instance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_instance_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RoomInstanceDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_instance_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomInstanceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_instance_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_instance_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoomInstanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_instance_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListGameHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_instance_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListGameHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_instance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_instance_proto_goTypes,
		DependencyIndexes: file_room_instance_proto_depIdxs,
		MessageInfos:      file_room_instance_proto_msgTypes,
	}.Build()
	File_room_instance_proto = out.File
	file_room_instance_proto_rawDesc = nil
	file_room_instance_proto_goTypes = nil
	file_room_instance_proto_depIdxs = nil
}
