// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: room_member.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomMemberDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomMemberId int64  `protobuf:"varint,1,opt,name=roomMemberId,proto3" json:"roomMemberId,omitempty"`
	RoomId       int64  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId       int64  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName     string `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	NickName     string `protobuf:"bytes,5,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Role         int32  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	AddTime      string `protobuf:"bytes,7,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Online       bool   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	CustomData   string `protobuf:"bytes,9,opt,name=customData,proto3" json:"customData,omitempty"`
}

func (x *RoomMemberDto) Reset() {
	*x = RoomMemberDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomMemberDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMemberDto) ProtoMessage() {}

func (x *RoomMemberDto) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMemberDto.ProtoReflect.Descriptor instead.
func (*RoomMemberDto) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{0}
}

func (x *RoomMemberDto) GetRoomMemberId() int64 {
	if x != nil {
		return x.RoomMemberId
	}
	return 0
}

func (x *RoomMemberDto) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMemberDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomMemberDto) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RoomMemberDto) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *RoomMemberDto) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *RoomMemberDto) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

func (x *RoomMemberDto) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *RoomMemberDto) GetCustomData() string {
	if x != nil {
		return x.CustomData
	}
	return ""
}

type ListRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *ListRoomMemberRequest) Reset() {
	*x = ListRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomMemberRequest) ProtoMessage() {}

func (x *ListRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*ListRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{1}
}

func (x *ListRoomMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type ListRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    []*RoomMemberDto `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total   int32            `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListRoomMemberResponse) Reset() {
	*x = ListRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomMemberResponse) ProtoMessage() {}

func (x *ListRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*ListRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoomMemberResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListRoomMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListRoomMemberResponse) GetData() []*RoomMemberDto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListRoomMemberResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InviteRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RoomId int64 `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *InviteRoomMemberRequest) Reset() {
	*x = InviteRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomMemberRequest) ProtoMessage() {}

func (x *InviteRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{3}
}

func (x *InviteRoomMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InviteRoomMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type InviteRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InviteRoomMemberResponse) Reset() {
	*x = InviteRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRoomMemberResponse) ProtoMessage() {}

func (x *InviteRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{4}
}

func (x *InviteRoomMemberResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InviteRoomMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserRoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomMemberId int64  `protobuf:"varint,1,opt,name=roomMemberId,proto3" json:"roomMemberId,omitempty"`
	RoomId       int64  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId       int64  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Role         int32  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	AddTime      string `protobuf:"bytes,7,opt,name=addTime,proto3" json:"addTime,omitempty"`
}

func (x *UserRoomMember) Reset() {
	*x = UserRoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoomMember) ProtoMessage() {}

func (x *UserRoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoomMember.ProtoReflect.Descriptor instead.
func (*UserRoomMember) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{5}
}

func (x *UserRoomMember) GetRoomMemberId() int64 {
	if x != nil {
		return x.RoomMemberId
	}
	return 0
}

func (x *UserRoomMember) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *UserRoomMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRoomMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserRoomMember) GetAddTime() string {
	if x != nil {
		return x.AddTime
	}
	return ""
}

type GetUserRoomMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *GetUserRoomMemberRequest) Reset() {
	*x = GetUserRoomMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRoomMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomMemberRequest) ProtoMessage() {}

func (x *GetUserRoomMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomMemberRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoomMemberRequest) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRoomMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type GetUserRoomMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *UserRoomMember `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserRoomMemberResponse) Reset() {
	*x = GetUserRoomMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_room_member_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRoomMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoomMemberResponse) ProtoMessage() {}

func (x *GetUserRoomMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_member_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoomMemberResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoomMemberResponse) Descriptor() ([]byte, []int) {
	return file_room_member_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRoomMemberResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserRoomMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserRoomMemberResponse) GetData() *UserRoomMember {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_room_member_proto protoreflect.FileDescriptor

var file_room_member_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x0d, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72,
	0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x16, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x44, 0x74, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x49, 0x0a, 0x17, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x18, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f,
	0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x71,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0xdc, 0x02, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x64, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x15, 0x12, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2d,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x74, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x3a, 0x01, 0x2a,
	0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x72, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f,
	0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x6f, 0x6f, 0x6d, 0x2d, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x42, 0x14, 0x5a, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_room_member_proto_rawDescOnce sync.Once
	file_room_member_proto_rawDescData = file_room_member_proto_rawDesc
)

func file_room_member_proto_rawDescGZIP() []byte {
	file_room_member_proto_rawDescOnce.Do(func() {
		file_room_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_room_member_proto_rawDescData)
	})
	return file_room_member_proto_rawDescData
}

var file_room_member_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_room_member_proto_goTypes = []any{
	(*RoomMemberDto)(nil),             // 0: v1.RoomMemberDto
	(*ListRoomMemberRequest)(nil),     // 1: v1.ListRoomMemberRequest
	(*ListRoomMemberResponse)(nil),    // 2: v1.ListRoomMemberResponse
	(*InviteRoomMemberRequest)(nil),   // 3: v1.InviteRoomMemberRequest
	(*InviteRoomMemberResponse)(nil),  // 4: v1.InviteRoomMemberResponse
	(*UserRoomMember)(nil),            // 5: v1.UserRoomMember
	(*GetUserRoomMemberRequest)(nil),  // 6: v1.GetUserRoomMemberRequest
	(*GetUserRoomMemberResponse)(nil), // 7: v1.GetUserRoomMemberResponse
}
var file_room_member_proto_depIdxs = []int32{
	0, // 0: v1.ListRoomMemberResponse.data:type_name -> v1.RoomMemberDto
	5, // 1: v1.GetUserRoomMemberResponse.data:type_name -> v1.UserRoomMember
	1, // 2: v1.RoomMember.ListRoomMember:input_type -> v1.ListRoomMemberRequest
	3, // 3: v1.RoomMember.InviteRoomMember:input_type -> v1.InviteRoomMemberRequest
	6, // 4: v1.RoomMember.GetUserRoomMember:input_type -> v1.GetUserRoomMemberRequest
	2, // 5: v1.RoomMember.ListRoomMember:output_type -> v1.ListRoomMemberResponse
	4, // 6: v1.RoomMember.InviteRoomMember:output_type -> v1.InviteRoomMemberResponse
	7, // 7: v1.RoomMember.GetUserRoomMember:output_type -> v1.GetUserRoomMemberResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_room_member_proto_init() }
func file_room_member_proto_init() {
	if File_room_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_room_member_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RoomMemberDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InviteRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InviteRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UserRoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserRoomMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_room_member_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserRoomMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_room_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_member_proto_goTypes,
		DependencyIndexes: file_room_member_proto_depIdxs,
		MessageInfos:      file_room_member_proto_msgTypes,
	}.Build()
	File_room_member_proto = out.File
	file_room_member_proto_rawDesc = nil
	file_room_member_proto_goTypes = nil
	file_room_member_proto_depIdxs = nil
}
