// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/StellrisJAY/cloud-emu/gamesrv/internal/conf"
	"github.com/StellrisJAY/cloud-emu/gamesrv/internal/server"
	"github.com/StellrisJAY/cloud-emu/gamesrv/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	gameServer := service.NewGameService()
	grpcServer := server.NewGRPCServer(confServer, gameServer, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, confServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
