server:
  http:
    addr: 0.0.0.0:8020
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9020
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:12345678@tcp(localhost:3306)/cloudemu_base?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  serverIp: 127.0.0.1
  port: 8848
  userName: nacos
  password: nacos
  namespaceId: public