// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/StellrisJAY/cloud-emu/platform/internal/biz"
	"github.com/StellrisJAY/cloud-emu/platform/internal/conf"
	"github.com/StellrisJAY/cloud-emu/platform/internal/data"
	"github.com/StellrisJAY/cloud-emu/platform/internal/server"
	"github.com/StellrisJAY/cloud-emu/platform/internal/service"
	"github.com/StellrisJAY/cloud-emu/platform/internal/util"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	node := util.NewSnowflakeGenerator(confServer)
	userUseCase := biz.NewUserUseCase(userRepo, node)
	userServer := service.NewUserService(userUseCase)
	roomRepo := data.NewRoomRepo(dataData)
	roomUseCase := biz.NewRoomUseCase(roomRepo, node)
	roomServer := service.NewRoomService(roomUseCase)
	grpcServer := server.NewGRPCServer(confServer, userServer, roomServer, logger)
	httpServer := server.NewHTTPServer(confServer, userServer, roomServer, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
