server:
  http:
    addr: 0.0.0.0:8020
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9020
    timeout: 1s
  nodeId: 1020
data:
  database:
    driver: mysql
    source: root:12345678@tcp(172.17.0.1:3306)/cloudemu_base?parseTime=True&loc=Local
  redis:
    addr: 172.17.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    username: redis
    password: redis
  mongodb:
    host: 172.17.0.1:27017
registry:
  scheme: consul
  serverIp: 172.17.0.1
  port: 8500
  userName: helloworld
  password: helloworld
  namespaceId: public
webrtc:
  portMin: 60000
  portMax: 65535
  iceServers:
    - url: stun:localhost:3478
      username:
      credential:
    - url: turn:localhost:3478
      username: username
      credential: password
